# fly.toml app configuration file generated for alist-yzcfxw on 2025-05-24T11:31:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'alist-yzcfxw'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 5244
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
